import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar/NavBar'
import Footer from '@/components/Footer/Footer'
import NotFound from './not-found'
import { notFound } from 'next/navigation'
import { Providers } from './providers'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { LocaleProvider } from '@/LocaleContext'
import { NextIntlClientProvider, useMessages } from 'next-intl'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const locales = ['en', 'pt', 'fr', 'de', 'it', 'jp', 'kr', 'cn'];

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode,
  params: { locale: string }
}) {

  if (!locales || !locales.includes(locale)) {
    NotFound();
  }

  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Providers>
          <LocaleProvider locale={locale}>
            <NextIntlClientProvider locale={locale} messages={messages}>
              <div className='container'>
                <NavBar locale={locale} />
                {children}
                <ToastContainer />
                <Footer />
              </div>
            </NextIntlClientProvider>
          </LocaleProvider>
        </Providers>
      </body>
    </html>
  )
}
